#set leader + r to reload tmux.conf
unbind r
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf

# set leader key to ctrl+s
set -g prefix C-s

# navigate panes using vim keymaps
setw -g mode-keys vi 
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# allow mouse scrolling in tmux terminals
set -g mouse on

# list of tpm plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# config lines for plugins
set -g @dracula-show-powerline true
set -g @dracula-transparent-powerline-bg true
set -g @dracula-show-flags true
set -g @dracula-show-empty-plugins false
set -g @dracula-refresh-rate 
set -g @dracula-plugins "time"
set -g @dracula-show-left-icon session
set -g @dracula-time-format "%F %R"
set -g @continuum-restore 'on'

# status position
set -g status-position top
set -g base-index 1
set -g pane-base-index 1

# init tmux plugin manager (keep at very bottom of tmux.conf)
run $XDG_CONFIG_HOME/tmux/plugins/tpm/tpm

